---
# - name: Apply security configuartion
#   import_playbook: security.yaml

- name: Deploy applications
  hosts: myserver
  become: false

  tasks:
    - name: Check if container exists
      community.docker.docker_container_info:
        name: "{{ docker_container_name }}"
      register: container_info
      failed_when: false

    # Stop existing container
    - name: Stop existing container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: stopped
      when: (container_info.containers | default([])) | length > 0

    # Remove existing container
    - name: Remove existing container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: absent
      when: (container_info.containers | default([])) | length > 0

    # Run new container
    - name: Run new Docker container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "3000:3000"
