---
# - name: Apply security configuartion
#   import_playbook: security.yaml

- name: Deploy applications
  hosts: myserver
  become: false

  tasks:
    # Stop docker existing container
    - name: Stop existing container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: stopped
      register: stop_result
      failed_when:
        - stop_result.failed
        - "'No such container' not in (stop_result.msg | default(''))"

    # Remove the old container
    - name: Remove existing container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: absent
      register: remove_result
      failed_when:
        - remove_result.failed
        - "'No such container' not in (remove_result.msg | default(''))"

    # Run new container
    - name: Run new Docker container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "3000:3000"
