---
- name: Ensure security configurations
  hosts: all
  become: yes
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        only_upgrade: yes
        cache_valid_time: 3600

    - name: Ensure unattended-upgrades is installed
      apt:
        name: unattended-upgrades
        state: present

    - name: Enable automatic security updates
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";

    - name: Run unattended upgrades to apply security patches
      command: unattended-upgrade -d
      register: unattened_result
      changed_when: "'Packages that will be upgraded:' in unattended_result.stdout"
