---
- name: Ensure security configurations
  hosts: all
  become: true
  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        only_upgrade: true
        cache_valid_time: 3600

    - name: Ensure unattended-upgrades is installed
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present

    - name: Enable automatic security updates
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        mode: "0644"

    - name: Run unattended upgrades to apply security patches
      ansible.builtin.command: unattended-upgrade -d
      register: unattened_result
      changed_when: "'Packages that will be upgraded:' in unattended_result.stdout"
