name: CI/CD Workflow
on:
  pull_request:
    branches: ["main", "dev", "release*"]
  push:
    branches: ["main", "dev", "release*"]
jobs:
  setup:
    name: Setup Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python Virtual Environment
        run: |
          # Create virtual environment
          python3 -m venv ~/ansible-venv

          # Activate and install packages
          source ~/ansible-venv/bin/activate
          pip install ansible-core docker

          # Install Docker collection
          ansible-galaxy collection install community.docker

          # Make sure venv is available for subsequent steps
          echo "source ~/ansible-venv/bin/activate" >> ~/.bashrc

  lint-javascript:
    name: ESLint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        working-directory: ./coffee-project
        run: npm install
      - name: Run ESLint
        working-directory: ./coffee-project
        run: npm run lint

  lint-ansible:
    name: Ansible Lint
    runs-on: self-hosted
    needs: [setup]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.8.2

  test:
    name: Runs Tests
    runs-on: self-hosted
    needs: [lint-javascript, lint-ansible]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        working-directory: ./coffee-project
        run: npm install
      - name: Run Tests
        working-directory: ./coffee-project
        run: npm test

  build:
    name: Build Docker Image
    runs-on: self-hosted
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        working-directory: ./coffee-project
        run: docker build -t coffee-project:latest .

  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Ansible Playbook
        run: |
          source ~/ansible-venv/bin/activate
          ansible-playbook -i ansible/hosts ansible/playbook.yaml
